# Generated by Django 2.2.5 on 2022-10-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatenHit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateField(auto_now_add=True, unique=True, verbose_name='日志产生时间')),
                ('hit_count', models.IntegerField(verbose_name='命中数量')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('gender', models.IntegerField(verbose_name='性别：1-男 2-女')),
                ('password', models.CharField(max_length=256, null=True, verbose_name='密码')),
            ],
        ),
    ]
